version: "3.6"

services:
  puppeteer-pdf:
    container_name: puppeteer-pdf
    build: .
    volumes:
      - $HOME/.aws/:/root/.aws/
      - ./output/:/var/task/output/
    ports:
      - "9000:8080"
    env_file:
      - .env